export const PERSIST_REHYDRATE = 'persist/REHYDRATE';

// LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// USER
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_CREATED_SUCCESS = 'REGISTER_CREATED_SUCCESS';
export const REGISTER_UPDATED_SUCCESS = 'REGISTER_UPDATED_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';

// ADDRESS
export const ADDRESS_REGISTER_REQUEST = 'ADDRESS_REGISTER_REQUEST';
export const ADDRESS_REGISTER_SUCCESS = 'ADDRESS_REGISTER_SUCCESS';
export const ADDRESS_REGISTER_FAILURE = 'ADDRESS_REGISTER_FAILURE';
